### PR TITLE
ENH: constrained_layout benchmark

### PR DESCRIPTION
**Pull request by jklymak**
... add benchmarks for constrained_layout...

### CODE REVIEW

**Comment by QuLogic** [comment]
So kiwisolver just had a release with some performance improvements, so I'm going to check that out and then merge this.

**Comment by QuLogic** [comment]
`constrained_layout.time_subplots_colorbar` times out for `n=5` for me (with older kiwisolver 1.2.0); how long does it take for you?

**Comment by QuLogic** [comment]
It also times out with kiwi 1.3.0, and actually times out on the Actions run, but asv doesn't exit with an error code (I'll look into that soon.)

**Comment by jklymak** [comment]
What matplotlib?  Master gives: 

```
[ 14.71%] ··· constrained_layout.time_subplots                                                                                            ok
[ 14.71%] ··· === =========
               n
              --- ---------
               1   193±0ms
               2   307±0ms
               5   1.08±0s
              === =========

[ 17.65%] ··· constrained_layout.time_subplots_colorbar                                                                                   ok
[ 17.65%] ··· === =========
               n
              --- ---------
               1   152±0ms
               2   569±0ms
               5   2.40±0s
              === =========
```

**Comment by jklymak** [comment]
OK on 3.3.2 the colorbar test indeed appears to time out.  I guess the number of constraints is too much...  

EDIT: 4x4 seems OK at 6 s, though we could make it a bit faster

**Comment by QuLogic** [comment]
Ah, okay, that was with 3.2.2; it is indeed much better with master. If this is something that's eventually fixed, then maybe it's fine to keep there.

**Comment by jklymak** [comment]
Its interesting because the old version is slightly faster until  you get to 4x4 or more, and then the new version is *far* faster.  But it would be nice to have the benchmark back in time, so suggest we do a 4x4 case...

**Comment by jklymak** [comment]
I'm still not clear what to do about the conflict with `results/benchmarks.json`.

**Comment by QuLogic** [comment]
Rebase and then commit it as it comes out of `asv dev` (unfortunately, I think this means you'll have conflicts with your other PR.)

**Pull request merged**
