### PR TITLE
ENH: benchmark date conversion

### PR DESCRIPTION
**Pull request by jklymak**
Checks that date conversion doesn't change speed too drastically.  Related to https://github.com/matplotlib/matplotlib/pull/18756

### CODE REVIEW

**Comment by QuLogic** [comment]
Let's see if a re-open will run the new CI.

**Comment by jklymak** [comment]
Should `benchmarks.json` be in the commit?

**Comment by QuLogic** [comment]
That's a good question; I think maybe I should have updated them in #4 for the flake8 fixes. And then maybe add another lint to check it? I'll have to look at other repos to see best practices.

**Comment by QuLogic** [comment]
Alright, I've opened #6 that should check this as well, as it seems a good idea to reduce churn on developer's machines.

**Pull request merged**
